# Generated by Django 4.2.2 on 2023-11-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Concepts', models.TextField()),
                ('Text', models.TextField()),
                ('References', models.TextField()),
                ('Definition', models.TextField()),
                ('Keywords', models.TextField()),
                ('Synonyms', models.TextField()),
                ('Predicate', models.TextField()),
                ('Object_Topic', models.TextField()),
            ],
            options={
                'db_table': 'output',
            },
        ),
    ]
