# Generated by Django 4.2.2 on 2023-11-16 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='output',
            name='Object_Topic',
        ),
        migrations.RemoveField(
            model_name='output',
            name='Predicate',
        ),
    ]
