# Generated by Django 4.2.2 on 2023-11-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_output_object_topic_remove_output_predicate'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='Object_Topic',
            field=models.CharField(default='Uncategorized', max_length=255),
        ),
        migrations.AddField(
            model_name='output',
            name='Predicate',
            field=models.CharField(default='Uncategorized', max_length=255),
        ),
    ]
